/* Mathe-Stadt 100 — Zonen, Missionen, Aufgabenbank */
var ZONES = [
  { id: "zahlen-tor", title: "Zahlen-Tor", description: "Hilf beim Öffnen des Tors mit Zahlen bis 100.", badgeName: "Zahlen-Tor-Abzeichen", visualKey: "zahlen-tor", microEffect: "gate" },
  { id: "baecker-gasse", title: "Bäcker-Gasse", description: "Brötchen zählen, rechnen und Geld wechseln.", badgeName: "Bäcker-Helfer", visualKey: "baecker-gasse", microEffect: "bakery" },
  { id: "bus-platz", title: "Bus-Platz", description: "Uhrzeit lesen und Fahrgäste zählen.", badgeName: "Bus-Starter", visualKey: "bus-platz", microEffect: "bus" },
  { id: "einmaleins-werkstatt", title: "Einmaleins-Werkstatt", description: "Zahnräder und Kisten — 4er- und 8er-Reihe.", badgeName: "Einmaleins-Schrauber", visualKey: "einmaleins-werkstatt", microEffect: "workshop" },
  { id: "umkehr-laden", title: "Umkehr-Laden", description: "Teile gerecht verteilen — Umkehraufgaben.", badgeName: "Umkehr-Profi", visualKey: "umkehr-laden", microEffect: "shop" },
  { id: "knobel-turm", title: "Knobel-Turm", description: "Knifflige Wege und Rechenrätsel.", badgeName: "Knobel-Kletterer", visualKey: "knobel-turm", microEffect: "tower" },
  { id: "schatzplatz", title: "Schatzplatz", description: "Der Mathe-Schatz für das große Fest.", badgeName: "Mathe-Fest-Held", visualKey: "schatzplatz", microEffect: "treasure" }
];

var MISSIONS = [
  { id: "zt-m1", zoneId: "zahlen-tor", missionTitle: "Das Tor braucht Zahlenschlüssel", missionIntro: "Der Torwächter findet die richtigen Zahlen nicht. Hilf ihm, das Stadttor zu öffnen.", visualKey: "zahlen-tor", taskIds: ["zt-01", "zt-02", "zt-03", "zt-04", "zt-05"], rewardText: "Das Tor öffnet sich!", cityChangeText: "Ein neuer Weg in die Stadt ist frei.", microEffect: "gate" },
  { id: "zt-m2", zoneId: "zahlen-tor", missionTitle: "Festbanner mit Zahlen", missionIntro: "Fürs Mathe-Fest fehlen noch die richtigen Zahlen auf dem Banner.", visualKey: "zahlen-tor", taskIds: ["zt-06", "zt-07", "zt-08", "zt-09", "zt-10"], rewardText: "Das Banner leuchtet!", cityChangeText: "Die Stadt sieht schon festlicher aus.", microEffect: "gate" },
  { id: "zt-m3", zoneId: "zahlen-tor", missionTitle: "Wegweiser richten", missionIntro: "Die Wegweiser zeigen falsche Vergleiche. Sortiere die Zahlen.", visualKey: "zahlen-tor", taskIds: ["zt-11", "zt-12", "zt-13", "zt-14", "zt-15"], rewardText: "Alle Wegweiser stimmen!", cityChangeText: "Niemand verläuft sich mehr.", microEffect: "gate" },
  { id: "bg-m1", zoneId: "baecker-gasse", missionTitle: "Brötchen fürs Fest", missionIntro: "Die Bäckerei muss genug Brötchen für das Fest backen.", visualKey: "baecker-gasse", taskIds: ["bg-01", "bg-02", "bg-03", "bg-04", "bg-05"], rewardText: "Der Ofen ist voll!", cityChangeText: "Es duftet nach frischen Brötchen.", microEffect: "bakery" },
  { id: "bg-m2", zoneId: "baecker-gasse", missionTitle: "An der Kasse", missionIntro: "Kunden bezahlen mit Münzen. Hilf, das Geld zusammenzurechnen.", visualKey: "baecker-gasse", taskIds: ["bg-06", "bg-07", "bg-08", "bg-09", "bg-10"], rewardText: "Die Kasse stimmt!", cityChangeText: "Der Bäcker kann einkaufen gehen.", microEffect: "bakery" },
  { id: "bg-m3", zoneId: "baecker-gasse", missionTitle: "Vorräte zählen", missionIntro: "Wie viele Zutaten fehlen noch in der Speisekammer?", visualKey: "baecker-gasse", taskIds: ["bg-11", "bg-12", "bg-13", "bg-14", "bg-15"], rewardText: "Alles ist vorbereitet!", cityChangeText: "Die Bäcker-Gasse ist startklar.", microEffect: "bakery" },
  { id: "bp-m1", zoneId: "bus-platz", missionTitle: "Der Bus kommt!", missionIntro: "Am Bus-Platz muss die Uhrzeit stimmen, damit der Bus pünktlich fährt.", visualKey: "bus-platz", taskIds: ["bp-01", "bp-02", "bp-03", "bp-04", "bp-05"], rewardText: "Der Bus fährt los!", cityChangeText: "Das Bus-Schild leuchtet.", microEffect: "bus" },
  { id: "bp-m2", zoneId: "bus-platz", missionTitle: "Fahrplan retten", missionIntro: "Hilf: Wie viele Kinder passen noch in den Bus?", visualKey: "bus-platz", taskIds: ["bp-06", "bp-07", "bp-08", "bp-09", "bp-10"], rewardText: "Der Fahrplan passt!", cityChangeText: "Alle Sitze sind gezählt.", microEffect: "bus" },
  { id: "bp-m3", zoneId: "bus-platz", missionTitle: "Ausflug zum Fest", missionIntro: "Die Klasse fährt gemeinsam zum Mathe-Fest.", visualKey: "bus-platz", taskIds: ["bp-11", "bp-12", "bp-13", "bp-14", "bp-15"], rewardText: "Alle sind angekommen!", cityChangeText: "Der Bus-Platz ist bereit.", microEffect: "bus" },
  { id: "ew-m1", zoneId: "einmaleins-werkstatt", missionTitle: "Zahnräder sortieren", missionIntro: "In der Werkstatt müssen Zahnräder in Kisten gepackt werden.", visualKey: "einmaleins-werkstatt", taskIds: ["ew-01", "ew-02", "ew-03", "ew-04", "ew-05"], rewardText: "Die Maschine läuft!", cityChangeText: "Ein Zahnrad dreht sich.", microEffect: "workshop" },
  { id: "ew-m2", zoneId: "einmaleins-werkstatt", missionTitle: "4er- und 8er-Bestellung", missionIntro: "Die Stadt bestellt Teile in gleich großen Gruppen.", visualKey: "einmaleins-werkstatt", taskIds: ["ew-06", "ew-07", "ew-08", "ew-09", "ew-10", "ew-11"], rewardText: "Die Bestellung ist komplett!", cityChangeText: "Noch mehr Zahnräder drehen sich.", microEffect: "workshop" },
  { id: "ew-m3", zoneId: "einmaleins-werkstatt", missionTitle: "Festwagen bauen", missionIntro: "Für den Festwagen braucht es viele gleiche Teile.", visualKey: "einmaleins-werkstatt", taskIds: ["ew-12", "ew-13", "ew-14", "ew-15", "ew-16", "ew-17", "ew-18", "ew-19", "ew-20"], rewardText: "Der Festwagen steht!", cityChangeText: "Die Werkstatt glänzt.", microEffect: "workshop" },
  { id: "ul-m1", zoneId: "umkehr-laden", missionTitle: "Kisten verteilen", missionIntro: "Im Laden müssen Kugeln fair in Körbe gelegt werden.", visualKey: "umkehr-laden", taskIds: ["ul-01", "ul-02", "ul-03", "ul-04", "ul-05"], rewardText: "Alle Körbe sind voll!", cityChangeText: "Eine Kiste wird gefüllt.", microEffect: "shop" },
  { id: "ul-m2", zoneId: "umkehr-laden", missionTitle: "Regale füllen", missionIntro: "Wie viele Sticker passen auf jedes Regalfach?", visualKey: "umkehr-laden", taskIds: ["ul-06", "ul-07", "ul-08", "ul-09", "ul-10"], rewardText: "Die Regale sind ordentlich!", cityChangeText: "Der Laden sieht tidy aus.", microEffect: "shop" },
  { id: "ul-m3", zoneId: "umkehr-laden", missionTitle: "Fair teilen", missionIntro: "Die Kinder teilen Material für das Fest.", visualKey: "umkehr-laden", taskIds: ["ul-11", "ul-12", "ul-13", "ul-14", "ul-15"], rewardText: "Jeder hat gleich viel!", cityChangeText: "Der Umkehr-Laden ist bereit.", microEffect: "shop" },
  { id: "kt-m1", zoneId: "knobel-turm", missionTitle: "Turmschritte", missionIntro: "Im Turm führen Rechenwege nach oben.", visualKey: "knobel-turm", taskIds: ["kt-01", "kt-02", "kt-03", "kt-04", "kt-05"], rewardText: "Eine Etage höher!", cityChangeText: "Das Schloss im Turm leuchtet.", microEffect: "tower" },
  { id: "kt-m2", zoneId: "knobel-turm", missionTitle: "Schatz-Rätsel", missionIntro: "Vor dem Schatz brauchst du kluge Rechenwege.", visualKey: "knobel-turm", taskIds: ["kt-06", "kt-07", "kt-08", "kt-09", "kt-10"], rewardText: "Das Rätsel ist gelöst!", cityChangeText: "Der Knobel-Turm ist gemeistert.", microEffect: "tower" },
  { id: "sp-m1", zoneId: "schatzplatz", missionTitle: "Fest-Check", missionIntro: "Kurz vor dem Fest: letzte Aufgaben für die Stadt.", visualKey: "schatzplatz", taskIds: ["sp-01", "sp-02", "sp-03", "sp-04", "sp-05"], rewardText: "Die Stadt ist fast fertig!", cityChangeText: "Lichter am Festplatz gehen an.", microEffect: "treasure" },
  { id: "sp-m2", zoneId: "schatzplatz", missionTitle: "Mathe-Schatz öffnen", missionIntro: "Nur wer alles gut kann, öffnet den großen Schatz.", visualKey: "schatzplatz", taskIds: ["sp-06", "sp-07", "sp-08", "sp-09", "sp-10"], rewardText: "Der Schatz ist offen!", cityChangeText: "Die Mathe-Stadt ist festbereit!", microEffect: "treasure" }
];

var TASK_BANK = [
  { id: "zt-01", zone: "zahlen-tor", mission: "zt-m1", sceneText: "Am Tor hängen Schlösser mit der Zahl 52. Der Wächter braucht die Einer.", question: "Wie viele Einer hat die Zahl 52?", answers: ["2", "5", "50", "25"], correctAnswer: "2", feedback: { "5": "Das sind die Zehner.", "50": "Das sind fünf Zehner.", "25": "Nur die letzte Ziffer zählt." }, tip: "Die Einer stehen ganz rechts.", successText: "Klick — ein Schloss springt auf!", pureMath: false },
  { id: "zt-02", zone: "zahlen-tor", mission: "zt-m1", sceneText: "Für das Tor brauchst du die Zehner von 70.", question: "Wie viele Zehner hat die Zahl 70?", answers: ["0", "7", "10", "70"], correctAnswer: "7", feedback: { "0": "70 hat mehr als null Zehner.", "10": "Ein Zehner zu viel.", "70": "70 ist die ganze Zahl." }, tip: "Die Zehner stehen links.", successText: "Noch ein Licht am Tor!", pureMath: false },
  { id: "zt-03", zone: "zahlen-tor", mission: "zt-m1", sceneText: "Der Schlüssel zeigt: 4 Zehner und 3 Einer.", question: "Welche Zahl passt?", answers: ["34", "43", "7", "403"], correctAnswer: "43", feedback: { "34": "Zehner und Einer sind vertauscht.", "7": "4 und 3 addiert ist nicht die Zahl.", "403": "Zu viele Stellen." }, tip: "40 + 3 = ?", pureMath: false },
  { id: "zt-04", zone: "zahlen-tor", mission: "zt-m1", sceneText: "Ein Schild zeigt 6 Zehner und 1 Einer.", question: "Welche Zahl gehört darauf?", answers: ["16", "61", "7", "601"], correctAnswer: "61", feedback: { "16": "6 Zehner sind 60.", "7": "6 + 1 ist nicht die Zahl.", "601": "Zu groß." }, tip: "60 + 1", pureMath: false },
  { id: "zt-05", zone: "zahlen-tor", mission: "zt-m1", sceneText: "Der Wächter fragt nach 3 Zehnern und 9 Einern.", question: "Welche Zahl ist das?", answers: ["12", "39", "93", "309"], correctAnswer: "39", feedback: { "12": "3 + 9 ist nicht die Zahl.", "93": "Vertauscht.", "309": "Zu groß." }, tip: "30 + 9", pureMath: false },
  { id: "zt-06", zone: "zahlen-tor", mission: "zt-m2", sceneText: "Am Banner steht die Zahl vor 50.", question: "Was ist der Vorgänger von 50?", answers: ["49", "51", "40", "60"], correctAnswer: "49", feedback: { "51": "Das ist der Nachfolger.", "40": "Das ist zehn weniger.", "60": "Das ist zehn mehr." }, tip: "Ein Schritt zurück.", pureMath: false },
  { id: "zt-07", zone: "zahlen-tor", mission: "zt-m2", sceneText: "Nach der 99 kommt die nächste Zahl fürs Fest.", question: "Nachfolger von 99?", answers: ["98", "100", "89", "90"], correctAnswer: "100", feedback: { "98": "Das ist davor.", "89": "Nicht die nächste.", "90": "Noch nicht ganz." }, tip: "99 + 1", pureMath: false },
  { id: "zt-08", zone: "zahlen-tor", mission: "zt-m2", sceneText: "Ein Kind fragt: Was kommt vor 31?", question: "Vorgänger von 31?", answers: ["30", "32", "21", "41"], correctAnswer: "30", feedback: { "32": "Das ist danach.", "21": "Zehn weniger.", "41": "Zehn mehr." }, tip: "31 − 1", pureMath: true },
  { id: "zt-09", zone: "zahlen-tor", mission: "zt-m2", sceneText: "Die Lichterkette braucht die Zahl nach 67.", question: "Nachfolger von 67?", answers: ["66", "68", "57", "77"], correctAnswer: "68", feedback: { "66": "Das ist davor.", "57": "Zehn weniger.", "77": "Zehn mehr." }, tip: "67 + 1", pureMath: true },
  { id: "zt-10", zone: "zahlen-tor", mission: "zt-m2", sceneText: "Am Festzelt fehlt die Zahl vor 100.", question: "Vorgänger von 100?", answers: ["99", "101", "90", "110"], correctAnswer: "99", feedback: { "101": "Nachfolger.", "90": "Nicht direkt davor.", "110": "Zu groß." }, tip: "Direkt links von 100.", pureMath: false },
  { id: "zt-11", zone: "zahlen-tor", mission: "zt-m3", sceneText: "Zwei Wegweiser: 45 und 54.", question: "Welches Zeichen passt? 45 ___ 54", answers: ["<", ">", "=", "+"], correctAnswer: "<", feedback: { ">": "45 ist kleiner.", "=": "Nicht gleich.", "+": "Hier vergleichst du." }, tip: "Welche Zahl ist kleiner?", pureMath: true },
  { id: "zt-12", zone: "zahlen-tor", mission: "zt-m3", sceneText: "Die Straße teilt sich: 72 oder 27?", question: "72 ___ 27 — welches Zeichen?", answers: ["<", ">", "=", "·"], correctAnswer: ">", feedback: { "<": "72 ist größer.", "=": "Nicht gleich.", "·": "Kein Mal." }, tip: "Mehr Zehner?", pureMath: true },
  { id: "zt-13", zone: "zahlen-tor", mission: "zt-m3", sceneText: "Zwei Häuser haben dieselbe Hausnummer: 60.", question: "60 ___ 60", answers: ["<", ">", "=", "-"], correctAnswer: "=", feedback: { "<": "Gleich groß.", ">": "Gleich groß.", "-": "Gleichheit ist =." }, tip: "Gleiche Zahl.", pureMath: true },
  { id: "zt-14", zone: "zahlen-tor", mission: "zt-m3", sceneText: "Welches Festzelt ist größer?", question: "Größer: 38 oder 83?", answers: ["38", "83", "gleich", "121"], correctAnswer: "83", feedback: { "38": "Weniger Zehner.", "gleich": "Unterschiedlich.", "121": "Nur 38 und 83." }, tip: "Zehner vergleichen.", pureMath: false },
  { id: "zt-15", zone: "zahlen-tor", mission: "zt-m3", sceneText: "Für kleine Gäste: das kleinere Zelt.", question: "Kleiner: 91 oder 19?", answers: ["91", "19", "gleich", "110"], correctAnswer: "19", feedback: { "91": "Größer.", "gleich": "Unterschiedlich.", "110": "Nur 91 und 19." }, tip: "Weniger Zehner.", pureMath: false },

  { id: "bg-01", zone: "baecker-gasse", mission: "bg-m1", sceneText: "Der Bäcker backt 24 Brötchen und noch 15 dazu.", question: "Wie viele Brötchen sind es?", answers: ["9", "29", "39", "2415"], correctAnswer: "39", feedback: { "9": "Hier kommen Brötchen dazu.", "29": "Einer fehlen.", "2415": "Plus, nicht aneinanderhängen." }, tip: "24 + 15", successText: "Der Korb wird voller!", pureMath: false },
  { id: "bg-02", zone: "baecker-gasse", mission: "bg-m1", sceneText: "Von 50 Brezeln werden 18 verkauft.", question: "Wie viele bleiben?", answers: ["32", "42", "68", "5018"], correctAnswer: "32", feedback: { "42": "Zu viele übrig.", "68": "Mehr als am Anfang.", "5018": "Wegnehmen heißt: minus." }, tip: "50 − 18", successText: "Noch genug für das Fest!", pureMath: false },
  { id: "bg-03", zone: "baecker-gasse", mission: "bg-m1", sceneText: "Morgens 35, nachmittags 22 Stück Kuchen.", question: "Kuchen insgesamt?", answers: ["13", "47", "57", "3522"], correctAnswer: "57", feedback: { "13": "Das wäre die Differenz.", "47": "Zehner fehlen.", "3522": "Beide Teile addieren." }, tip: "35 + 22", successText: "Die Vitrine ist voll!", pureMath: false },
  { id: "bg-04", zone: "baecker-gasse", mission: "bg-m1", sceneText: "38 Plätzchen liegen auf dem Blech. Es kommen 27 dazu.", question: "Wie viele Plätzchen jetzt?", answers: ["11", "55", "65", "3827"], correctAnswer: "65", feedback: { "11": "Minus wäre falsch.", "55": "Zehnerübergang fehlt.", "3827": "Du hast die Zahlen aneinander geschrieben." }, tip: "38 + 27", successText: "Der Ofen duftet!", pureMath: false },
  { id: "bg-05", zone: "baecker-gasse", mission: "bg-m1", sceneText: "In der Bäckerei liegen 47 Plätzchen. 28 Plätzchen werden für das Mathe-Fest verkauft.", question: "Wie viele Plätzchen bleiben übrig?", answers: ["19", "29", "39", "75"], correctAnswer: "19", feedback: { "29": "Dann wären zu viele Plätzchen übrig.", "39": "Das wäre viel zu viel: du hättest zu wenig weggenommen.", "75": "Das wäre mehr als am Anfang — dann wären Plätzchen dazugekommen." }, tip: "47 − 28", successText: "Der Ofen duftet — und der Rest passt!", pureMath: false },
  { id: "bg-06", zone: "baecker-gasse", mission: "bg-m2", sceneText: "Ein Brötchen kostet 50 Cent. Du kaufst 4.", question: "Wie viel Cent zahlst du?", answers: ["54", "150", "200", "450"], correctAnswer: "200", feedback: { "54": "Plus statt Mal.", "150": "Zu wenig.", "450": "Zu viel." }, tip: "4 · 50 oder 50+50+50+50", successText: "Das Geld stimmt!", pureMath: false },
  { id: "bg-07", zone: "baecker-gasse", mission: "bg-m2", sceneText: "Du hast 2 Euro. Ein Brötchen kostet 80 Cent.", question: "Wie viel Cent bleiben?", answers: ["120", "100", "280", "820"], correctAnswer: "120", feedback: { "100": "20 Cent fehlen.", "280": "Zu viel übrig.", "820": "Minus, nicht anhängen." }, tip: "200 − 80 Cent", successText: "Wechselgeld passt!", pureMath: false },
  { id: "bg-08", zone: "baecker-gasse", mission: "bg-m2", sceneText: "3 Brötchen à 60 Cent.", question: "Wie viel Cent insgesamt?", answers: ["63", "160", "180", "360"], correctAnswer: "180", feedback: { "63": "Plus statt Mal.", "160": "Zu wenig.", "360": "Zu viel." }, tip: "3 · 60 oder 60+60+60", successText: "Die Kasse klingelt!", pureMath: false },
  { id: "bg-09", zone: "baecker-gasse", mission: "bg-m2", sceneText: "Du legst 1 Euro und 50 Cent hin. Es kosten 95 Cent.", question: "Wie viel Cent zurück?", answers: ["45", "55", "145", "195"], correctAnswer: "55", feedback: { "45": "10 Cent zu wenig.", "145": "Zu viel.", "195": "Falsch gerechnet." }, tip: "150 − 95", successText: "Richtiges Wechselgeld!", pureMath: false },
  { id: "bg-10", zone: "baecker-gasse", mission: "bg-m2", sceneText: "5 Freunde zahlen je 20 Cent.", question: "Wie viel Cent zusammen?", answers: ["25", "80", "100", "520"], correctAnswer: "100", feedback: { "25": "Plus statt Mal.", "80": "Zu wenig.", "520": "5 · 20, nicht 520." }, tip: "5 · 20", successText: "Genau 1 Euro!", pureMath: false },
  { id: "bg-11", zone: "baecker-gasse", mission: "bg-m3", sceneText: "Es fehlen noch Brötchen bis 80. Der Bäcker hat 52.", question: "Wie viele fehlen?", answers: ["18", "28", "38", "132"], correctAnswer: "28", feedback: { "18": "Zu wenig.", "38": "Zu viel.", "132": "Das wäre zu groß: 80 − 52 ist richtig." }, tip: "Von 52 bis 80: wie viele fehlen noch?", successText: "Jetzt weiß er, wie viele Brötchen noch gebraucht werden!", pureMath: false },
  { id: "bg-12", zone: "baecker-gasse", mission: "bg-m3", sceneText: "Im Mehlkorb liegen 34 Schaufeln Mehl. Für den Vorrat braucht die Bäckerin 50 Schaufeln.", question: "Wie viele Schaufeln Mehl fehlen noch?", answers: ["16", "26", "14", "84"], correctAnswer: "16", feedback: { "26": "Das wären zu viele — dann hättet ihr mehr als 50.", "14": "Fast. Für 50 braucht es noch 16, nicht 14.", "84": "So viel Mehl fehlt nicht. Es geht um die Lücke zwischen 34 und 50." }, tip: "50 − 34", successText: "Genug Mehl! Der Vorrat ist fertig.", pureMath: false },
  { id: "bg-13", zone: "baecker-gasse", mission: "bg-m3", sceneText: "Im Karton liegen 56 Eier. Für das Mathe-Fest kommen noch 13 Eier dazu.", question: "Wie viele Eier sind es insgesamt?", answers: ["59", "67", "69", "78"], correctAnswer: "69", feedback: { "59": "Zu wenig — da fehlen 10 Eier.", "67": "Fast. Es sind noch 2 Eier zu wenig.", "78": "Zu viel — dann wären es mehr als geplant." }, tip: "56 + 13", successText: "Der Karton ist voll — perfekt für das Fest!", pureMath: false },
  { id: "bg-14", zone: "baecker-gasse", mission: "bg-m3", sceneText: "Für den Zuckerguss braucht der Bäcker 35 Zuckerwürfel. In der Kiste sind 90 Stück.", question: "Wie viele Zuckerwürfel bleiben übrig?", answers: ["45", "55", "65", "125"], correctAnswer: "55", feedback: { "45": "Zu wenig — dann wären zu viele Zuckerwürfel verbraucht.", "65": "Zu viel — dann wären nur 25 weg.", "125": "Das kann nicht sein: 90 ist das Maximum." }, tip: "90 − 35", successText: "Die Vorräte stimmen! Alles ist bereit.", pureMath: false },
  { id: "bg-15", zone: "baecker-gasse", mission: "bg-m3", sceneText: "Lina kauft für 65 Cent. Sie hat 1 Euro.", question: "Wie viel Cent Wechselgeld?", answers: ["25", "35", "45", "165"], correctAnswer: "35", feedback: { "25": "10 zu wenig.", "45": "10 zu viel.", "165": "100 − 65." }, tip: "100 − 65", successText: "Einkauf geschafft!", pureMath: false },

  { id: "bp-01", zone: "bus-platz", mission: "bp-m1", sceneText: "Der Bus fährt um 8 Uhr. Die Uhr zeigt 7 Uhr.", question: "Wie viele Stunden noch?", answers: ["1", "2", "7", "8"], correctAnswer: "1", feedback: { "2": "Nur bis 8 Uhr.", "7": "Das ist jetzt.", "8": "Das ist Abfahrt." }, tip: "Von 7 bis 8.", successText: "Gleich geht der Bus!", pureMath: false },
  { id: "bp-02", zone: "bus-platz", mission: "bp-m1", sceneText: "Die Schulbus-Uhr zeigt halb 9.", question: "Welche Uhrzeit ist halb 9?", answers: ["8:30 Uhr", "9:00 Uhr", "8:00 Uhr", "9:30 Uhr"], correctAnswer: "8:30 Uhr", feedback: { "9:00 Uhr": "Das ist ganze 9 Uhr, nicht halb 9.", "8:00 Uhr": "Das ist zu früh — halb 9 ist später.", "9:30 Uhr": "Das wäre nach halb 9." }, tip: "Halb 9 ist 8:30 Uhr.", successText: "Die Uhr stimmt!", pureMath: false },
  { id: "bp-03", zone: "bus-platz", mission: "bp-m1", sceneText: "Um 10 Uhr kommt der Festbus. Es ist 8 Uhr.", question: "Wie viele Stunden warten?", answers: ["1", "2", "10", "18"], correctAnswer: "2", feedback: { "1": "Eine Stunde zu wenig.", "10": "Das ist Ankunft.", "18": "8 + 2 = 10." }, tip: "8 … 9 … 10", successText: "Noch 2 Stunden!", pureMath: false },
  { id: "bp-04", zone: "bus-platz", mission: "bp-m1", sceneText: "Ein Fahrplan: Abfahrt 14 Uhr, Ankunft 15 Uhr.", question: "Wie lange fährt der Bus?", answers: ["1 Stunde", "2 Stunden", "14 Stunden", "30 Minuten"], correctAnswer: "1 Stunde", feedback: { "2 Stunden": "Zu lang.", "14 Stunden": "Das ist Abfahrt.", "30 Minuten": "Von 14 bis 15 ist 1 Stunde." }, tip: "14 Uhr bis 15 Uhr.", successText: "Der Fahrplan passt!", pureMath: false },
  { id: "bp-05", zone: "bus-platz", mission: "bp-m1", sceneText: "Die Uhr am Platz zeigt 12 Uhr.", question: "12 Uhr — wie spricht man das?", answers: ["Mittag", "Mitternacht immer", "8 Uhr", "Halb 12"], correctAnswer: "Mittag", feedback: { "Mitternacht immer": "12 Uhr kann Mittag sein.", "8 Uhr": "Falsch.", "Halb 12": "Das wäre 11:30." }, tip: "Mittags um 12.", successText: "Mittagsbus!", pureMath: false },
  { id: "bp-06", zone: "bus-platz", mission: "bp-m2", sceneText: "Im Bus sind 42 Kinder. 15 steigen ein.", question: "Wie viele Kinder sind im Bus?", answers: ["27", "47", "57", "4215"], correctAnswer: "57", feedback: { "27": "Das wäre minus — es kommen Kinder dazu.", "47": "Zehner fehlen — es sind zu wenig dazugezählt.", "4215": "Plus heißt: zusammenrechnen, nicht aneinanderhängen." }, tip: "42 + 15", successText: "Alle haben Platz!", pureMath: false },
  { id: "bp-07", zone: "bus-platz", mission: "bp-m2", sceneText: "65 Sitze, 28 sind frei.", question: "Wie viele besetzt?", answers: ["37", "47", "93", "6528"], correctAnswer: "37", feedback: { "47": "Zu viele.", "93": "Zu viele.", "6528": "65 − 28." }, tip: "Gesamt minus frei.", successText: "Der Fahrer nickt!", pureMath: false },
  { id: "bp-08", zone: "bus-platz", mission: "bp-m2", sceneText: "29 Kinder warten. 34 sind schon im Bus.", question: "Kinder insgesamt?", answers: ["5", "53", "63", "2934"], correctAnswer: "63", feedback: { "5": "Das wäre minus.", "53": "Zehner fehlt.", "2934": "Du hast die Zahlen aneinander geschrieben." }, tip: "29 + 34", successText: "Alle gezählt!", pureMath: false },
  { id: "bp-09", zone: "bus-platz", mission: "bp-m2", sceneText: "100 km Route, 38 km sind geschafft.", question: "Wie viele km fehlen?", answers: ["62", "72", "138", "10038"], correctAnswer: "62", feedback: { "72": "Zu viel.", "138": "Plus.", "10038": "100 − 38." }, tip: "Reststrecke.", successText: "Fast am Fest!", pureMath: false },
  { id: "bp-10", zone: "bus-platz", mission: "bp-m2", sceneText: "Die Bus-Strecke hat schon 53 Kilometer geschafft. Danach kommen noch 38 Kilometer dazu.", question: "Wie viele Kilometer sind es zusammen?", answers: ["81", "91", "101", "85"], correctAnswer: "91", feedback: { "81": "Das wäre zu kurz.", "101": "Das wäre zu lang.", "85": "Da passen 53 und 38 nicht zusammen." }, tip: "53 + 38 = ?", successText: "Route klar!", pureMath: false },
  { id: "bp-11", zone: "bus-platz", mission: "bp-m3", sceneText: "Jedes Kind bringt 5 Luftballons. 6 Kinder.", question: "Luftballons insgesamt?", answers: ["11", "25", "30", "56"], correctAnswer: "30", feedback: { "11": "Plus.", "25": "Zu wenig.", "56": "Anhängen." }, tip: "6 · 5", successText: "Bunt am Bus!", pureMath: false },
  { id: "bp-12", zone: "bus-platz", mission: "bp-m3", sceneText: "Der Bus hat 4 Reihen mit je 10 Sitzen.", question: "Sitze insgesamt?", answers: ["14", "20", "40", "410"], correctAnswer: "40", feedback: { "14": "Plus.", "20": "Zu wenig.", "410": "4 · 10." }, tip: "4 · 10", successText: "Alle Sitze da!", pureMath: false },
  { id: "bp-13", zone: "bus-platz", mission: "bp-m3", sceneText: "Der Bus hat 81 Sitze. 29 Sitze sind noch frei.", question: "Wie viele Sitze sind besetzt?", answers: ["52", "62", "72", "110"], correctAnswer: "52", feedback: { "62": "Zu viele Sitze — dann wären es zu wenig freie.", "72": "Noch zu viel besetzt. 29 sind frei, nicht weniger.", "110": "Das kann nicht stimmen: 110 ist größer als 81." }, tip: "81 − 29", successText: "Bus startet!", pureMath: false },
  { id: "bp-14", zone: "bus-platz", mission: "bp-m3", sceneText: "2 Busse, je 40 Kinder.", question: "Kinder insgesamt?", answers: ["42", "60", "80", "240"], correctAnswer: "80", feedback: { "42": "Plus.", "60": "Zu wenig.", "240": "2 · 40." }, tip: "2 · 40", successText: "Alle unterwegs!", pureMath: false },
  { id: "bp-15", zone: "bus-platz", mission: "bp-m3", sceneText: "Am Bus-Platz warten 75 Kinder. 48 Kinder sind schon eingestiegen.", question: "Wie viele Kinder warten noch draußen?", answers: ["27", "37", "47", "123"], correctAnswer: "27", feedback: { "37": "Das wären 10 Kinder zu viel.", "47": "Zu viel — es fehlen noch Kinder, nicht zu viele.", "123": "Das ist viel zu groß. Es geht um die Wartenden." }, tip: "75 − 48", successText: "Fertig für das Fest!", pureMath: false },

  { id: "ew-01", zone: "einmaleins-werkstatt", mission: "ew-m1", sceneText: "In der Werkstatt stehen 7 Kisten. In jeder Kiste liegen 8 Zahnräder.", question: "Wie viele Zahnräder sind es zusammen?", answers: ["15", "48", "56", "64"], correctAnswer: "56", feedback: { "15": "Das sieht nach 7 + 8 aus. Hier brauchst du eine Malaufgabe.", "48": "Fast. Das ist eine 8er-Gruppe zu wenig.", "64": "Das ist eine 8er-Gruppe zu viel." }, tip: "Denke an die 8er-Reihe: 8, 16, 24, 32, 40, 48, 56.", successText: "Super! Die Zahnräder passen in die Maschine.", pureMath: false },
  { id: "ew-02", zone: "einmaleins-werkstatt", mission: "ew-m1", sceneText: "5 Kisten mit je 4 Muttern.", question: "Muttern insgesamt?", answers: ["9", "16", "20", "54"], correctAnswer: "20", feedback: { "9": "Plus statt Mal.", "16": "Eine Gruppe zu wenig.", "54": "Anhängen." }, tip: "5 · 4", successText: "Die Kiste ist voll!", pureMath: false },
  { id: "ew-03", zone: "einmaleins-werkstatt", mission: "ew-m1", sceneText: "6 Regale mit je 8 Teilen.", question: "Teile insgesamt?", answers: ["14", "42", "48", "68"], correctAnswer: "48", feedback: { "14": "Plus.", "42": "Zu wenig.", "68": "Anhängen." }, tip: "6 · 8", successText: "Regal gefüllt!", pureMath: false },
  { id: "ew-04", zone: "einmaleins-werkstatt", mission: "ew-m1", sceneText: "In der Werkstatt gibt es 3 Beutel. In jedem Beutel sind 8 Schrauben.", question: "Wie viele Schrauben sind es zusammen?", answers: ["11", "21", "24", "38"], correctAnswer: "24", feedback: { "11": "Das wären zu wenig Schrauben.", "21": "Das sieht nach Plus aus. Hier brauchst du Mal.", "38": "Das wären zu viele Schrauben." }, tip: "Denke an die 8er-Reihe: 8, 16, 24.", successText: "Beutel zu!", pureMath: false },
  { id: "ew-05", zone: "einmaleins-werkstatt", mission: "ew-m1", sceneText: "In der Werkstatt liegen Plättchen in 9 Reihen. In jeder Reihe sind 4 Plättchen.", question: "Wie viele Plättchen sind es insgesamt?", answers: ["13", "32", "36", "94"], correctAnswer: "36", feedback: { "13": "Das wären zu wenige Plättchen.", "32": "Das wären fast die richtige Menge. Es fehlen noch.", "94": "Das wäre viel zu viel." }, tip: "Zähle in 4er-Schritten bis zur 9. Reihe.", successText: "Plättchen sortiert!", pureMath: false },
  { id: "ew-06", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "In der Werkstatt stehen 4 Wagen. Auf jeden Wagen kommen 8 Räder.", question: "Räder an 4 Wagen mit je 8?", answers: ["12", "28", "32", "48"], correctAnswer: "32", feedback: { "12": "Das wären nur die Räder von 3 Wagen.", "28": "Das wären zu wenig Räder.", "48": "Das wären zu viele Räder." }, tip: "Denke an die 8er-Reihe: 8, 16, 24, 32.", successText: "Wagen fertig!", pureMath: false },
  { id: "ew-07", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "In der Werkstatt werden 7 Pakete gebaut. In jedem Paket sind 4 Teile.", question: "Teile in 7 Paketen à 4?", answers: ["11", "21", "28", "74"], correctAnswer: "28", feedback: { "11": "Das wären zu wenig Teile.", "21": "Das wären zu wenig Teile. Es fehlen noch.", "74": "Das wäre viel zu viel." }, tip: "Zähle die 4er-Reihe bis zur 7. Zahl.", successText: "Pakete fertig!", pureMath: false },
  { id: "ew-08", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "Es gibt 8 Reihen. In jeder Reihe sind 5 Haken.", question: "Haken in 8 Reihen à 5?", answers: ["13", "35", "40", "85"], correctAnswer: "40", feedback: { "13": "Das sind zu wenige Haken.", "35": "Fast. Bei 8 Reihen kommt noch ein bisschen dazu.", "85": "Das wäre viel zu viel." }, tip: "Zähle in 5er-Schritten bis 40.", successText: "Haken dran!", pureMath: false },
  { id: "ew-09", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "In der Werkstatt hängen 2 Lichterketten. Jede Kette hat 8 Lichter.", question: "Wie viele Lichter sind es zusammen?", answers: ["10", "14", "16", "28"], correctAnswer: "16", feedback: { "10": "Das wären zu wenige Lichter.", "14": "Das wäre fast richtig. Es fehlen noch 2 Lichter.", "28": "Das wäre viel zu viel." }, tip: "8 + 8: Denk an die 8er-Reihe.", successText: "Es leuchtet!", pureMath: false },
  { id: "ew-10", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "Für das Fest gibt es 10 Reihen. In jeder Reihe sind 4 Flaggen.", question: "Wie viele Flaggen sind es insgesamt?", answers: ["14", "36", "40", "104"], correctAnswer: "40", feedback: { "14": "Das wären zu wenige Flaggen.", "36": "Fast. Bei 10 Reihen kommt noch mehr dazu.", "104": "Das wäre viel zu viel." }, tip: "Zähle in 4er-Schritten bis 40.", successText: "Festflags bereit!", pureMath: false },
  { id: "ew-11", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "Für die Dekoration stehen 5 Tische bereit. Auf jeden Tisch kommen 8 Stühle.", question: "5 Tische mit je 8 Stühlen?", answers: ["13", "35", "40", "58"], correctAnswer: "40", feedback: { "13": "Das wären zu wenige Stühle.", "35": "Fast. Es fehlen noch ein paar Stühle.", "58": "Das wäre viel zu viel." }, tip: "Zähle die 8er-Reihe.", successText: "Alle Stühle da!", pureMath: false },
  { id: "ew-12", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für die Maschine liegen 20 Teile bereit. Die Teile sollen in Gruppen mit je 4 geteilt werden.", question: "Wie viele Kisten à 4 passen in 20?", answers: ["4", "5", "6", "24"], correctAnswer: "5", feedback: { "4": "Zu wenig Kisten.", "6": "Zu viele Kisten.", "24": "Das wären viel mehr Teile." }, tip: "4 · ? = 20", successText: "Kisten verteilt!", pureMath: false },
  { id: "ew-13", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "In der Werkstatt liegen 32 Schrauben bereit. Die Schrauben werden in Gruppen zu je 8 sortiert.", question: "Wie viele Achter-Gruppen in 32?", answers: ["3", "4", "5", "6"], correctAnswer: "4", feedback: { "3": "Zu wenig Gruppen.", "5": "Zu viel Gruppen.", "6": "Zu viel Gruppen." }, tip: "Zähle in 8er-Schritten: 8, 16, 24, 32", successText: "Achter passt!", pureMath: false },
  { id: "ew-14", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für die Maschine sollen 56 Teile in Gruppen zu je 8 sortiert werden.", question: "Wie viele Gruppen à 8 ergeben 56?", answers: ["6", "7", "8", "9"], correctAnswer: "7", feedback: { "6": "Zu wenig Gruppen.", "8": "Zu viel Gruppen.", "9": "Zu viel Gruppen." }, tip: "8er-Reihe bis 56", successText: "Richtig geteilt!", pureMath: false },
  { id: "ew-15", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für den Festwagen braucht es 28 Teile. Die Teile werden in 7 gleich große Pakete geteilt.", question: "7 Pakete mit wie vielen Teilen = 28?", answers: ["3", "4", "5", "6"], correctAnswer: "4", feedback: { "3": "Zu wenig Teile pro Paket.", "5": "Zu viel Teile pro Paket.", "6": "Zu viel Teile pro Paket." }, tip: "7 · ? = 28", successText: "Pakete stimmen!", pureMath: false },
  { id: "ew-16", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für die Lichterkette gibt es 9 Ketten. Jede Kette hat 8 Lichter.", question: "9 Ketten mit je 8 Lichtern?", answers: ["17", "63", "72", "89"], correctAnswer: "72", feedback: { "17": "Das wären viel zu wenige Lichter.", "63": "Fast. Es fehlen 9 Lichter.", "89": "Das wäre zu viel." }, tip: "8er-Reihe: 8, 16, 24, 32, 40, 48, 56, 64, 72", successText: "Die Stadt leuchtet!", pureMath: false },
  { id: "ew-17", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für den Festwagen gibt es 6 Wagen. Jeder Wagen bekommt 4 Räder.", question: "6 Wagen mit je 4 Rädern?", answers: ["10", "20", "24", "46"], correctAnswer: "24", feedback: { "10": "Das wäre zu wenig.", "20": "Fast. Es fehlen noch 4 Räder.", "46": "Das wäre zu viel." }, tip: "4er-Reihe bis 24", successText: "Festwagen rollt!", pureMath: false },
  { id: "ew-18", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für die Lichterwand liegen 48 Lichter bereit. Sie werden in Gruppen zu je 8 sortiert.", question: "48 Lichter in Gruppen à 8?", answers: ["5", "6", "7", "8"], correctAnswer: "6", feedback: { "5": "Zu wenig Gruppen.", "7": "Zu viele Gruppen.", "8": "Zu viele Gruppen — 8·8 wäre mehr." }, tip: "8er bis 48", successText: "Kette fertig!", pureMath: false },
  { id: "ew-19", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "In der Werkstatt stehen 2 Stapel. In jedem Stapel liegen 4 Teile.", question: "Wie viele Teile sind es zusammen?", answers: ["6", "8", "10", "24"], correctAnswer: "8", feedback: { "6": "Das wäre zu wenig.", "10": "Das wäre zu viel.", "24": "Das wäre viel zu viel." }, tip: "4 + 4", successText: "Kleine Maschine läuft!", pureMath: false },
  { id: "ew-20", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "In der Werkstatt stehen 5 Stapel. In jedem Stapel liegen 4 Teile.", question: "Wie viele Teile sind es zusammen?", answers: ["9", "16", "20", "54"], correctAnswer: "20", feedback: { "9": "Das wäre zu wenig.", "16": "Fast. Es fehlen noch 4 Teile.", "54": "Das wäre viel zu viel." }, tip: "4er-Reihe bis 20", successText: "Werkstatt fertig!", pureMath: false },
  { id: "ew-21", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "Am Festwagen braucht es 6 Räder pro Seite. 4 Seiten.", question: "Räder insgesamt?", answers: ["10", "20", "24", "64"], correctAnswer: "24", feedback: { "10": "Plus.", "20": "Zu wenig.", "64": "6·4." }, tip: "6 · 4", successText: "Seite montiert!", pureMath: false },
  { id: "ew-22", zone: "einmaleins-werkstatt", mission: "ew-m2", sceneText: "Es gibt 7 Reihen. In jeder Reihe sind 8 Lichter.", question: "Wie viele Lichter sind es zusammen?", answers: ["15", "48", "56", "78"], correctAnswer: "56", feedback: { "15": "Das wären viel zu wenige Lichter.", "48": "Fast. Es fehlen 8 Lichter.", "78": "Das wäre zu viel." }, tip: "8er-Reihe bis 56", successText: "Strebe fest!", pureMath: false },
  { id: "ew-23", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Der Meister packt 9 Beutel mit je 8 Schrauben.", question: "Schrauben gesamt?", answers: ["17", "64", "72", "98"], correctAnswer: "72", feedback: { "17": "Plus.", "64": "Eine Gruppe wenig.", "98": "Mal." }, tip: "9 · 8", successText: "Beutel voll!", pureMath: false },
  { id: "ew-24", zone: "einmaleins-werkstatt", mission: "ew-m3", sceneText: "Für den Festbogen gibt es 10 Reihen. In jeder Reihe sind 2 Schilder.", question: "Wie viele Schilder sind es zusammen?", answers: ["12", "18", "20", "102"], correctAnswer: "20", feedback: { "12": "Das wären zu wenige Schilder.", "18": "Fast. Es fehlen noch 2 Schilder.", "102": "Das wäre viel zu viel." }, tip: "2 · 10", successText: "Kette hält!", pureMath: false },
  { id: "ew-25", zone: "einmaleins-werkstatt", mission: "ew-m1", sceneText: "Am Festwagen hängen 7 Reihen. In jeder Reihe sind 4 Nägel.", question: "7 Reihen mit je 4 Nägeln?", answers: ["11", "24", "28", "47"], correctAnswer: "28", feedback: { "11": "Das wären zu wenige Nägel.", "24": "Fast. Es fehlen noch 4 Nägel.", "47": "Das wäre zu viel." }, tip: "4er-Reihe bis 28", successText: "Nagel rein!", pureMath: false },

  { id: "ul-01", zone: "umkehr-laden", mission: "ul-m1", sceneText: "20 Kugeln fair in 4 Körbe.", question: "Wie viele in jeden Korb?", answers: ["4", "5", "6", "16"], correctAnswer: "5", feedback: { "4": "Zu wenig.", "6": "Zu viel.", "16": "Plus." }, tip: "4 · ? = 20", successText: "Fair verteilt!", pureMath: false },
  { id: "ul-02", zone: "umkehr-laden", mission: "ul-m1", sceneText: "24 Sticker auf 6 Kinder.", question: "Jedes Kind bekommt?", answers: ["3", "4", "5", "18"], correctAnswer: "4", feedback: { "3": "Zu wenig.", "5": "Zu viel.", "18": "Minus." }, tip: "6 · ? = 24", successText: "Alle glücklich!", pureMath: false },
  { id: "ul-03", zone: "umkehr-laden", mission: "ul-m1", sceneText: "35 = 7 · ?", question: "7 Pakete mit gleich vielen?", answers: ["4", "5", "6", "28"], correctAnswer: "5", feedback: { "4": "Zu wenig.", "6": "Zu viel.", "28": "7·4=28." }, tip: "7 mal ?", successText: "Pakete gleich!", pureMath: false },
  { id: "ul-04", zone: "umkehr-laden", mission: "ul-m1", sceneText: "? · 5 = 30", question: "Wie viele Fünfer-Gruppen in 30?", answers: ["5", "6", "7", "25"], correctAnswer: "6", feedback: { "5": "Zu wenig.", "7": "Zu viel.", "25": "5·5=25." }, tip: "5er-Reihe", successText: "Körbe voll!", pureMath: false },
  { id: "ul-05", zone: "umkehr-laden", mission: "ul-m1", sceneText: "36 Kugeln in Kisten à 4.", question: "Wie viele Kisten?", answers: ["8", "9", "10", "32"], correctAnswer: "9", feedback: { "8": "Zu wenig.", "10": "Zu viel.", "32": "4·8=32." }, tip: "4 · ? = 36", successText: "Letzte Kiste!", pureMath: false },
  { id: "ul-06", zone: "umkehr-laden", mission: "ul-m2", sceneText: "40 = 8 · ?", question: "8 Regale mit gleich vielen?", answers: ["4", "5", "6", "32"], correctAnswer: "5", feedback: { "4": "Zu wenig.", "6": "Zu viel.", "32": "8·4." }, tip: "8 · ?", successText: "Regal gefüllt!", pureMath: false },
  { id: "ul-07", zone: "umkehr-laden", mission: "ul-m2", sceneText: "? · 4 = 36", question: "Wie oft passt 4 in 36?", answers: ["8", "9", "10", "32"], correctAnswer: "9", feedback: { "8": "Zu wenig.", "10": "Zu viel.", "32": "4·8." }, tip: "4er-Reihe", successText: "Ordentlich!", pureMath: false },
  { id: "ul-08", zone: "umkehr-laden", mission: "ul-m2", sceneText: "48 Teile, 8 Kisten.", question: "Pro Kiste?", answers: ["5", "6", "7", "40"], correctAnswer: "6", feedback: { "5": "Zu wenig.", "7": "Zu viel.", "40": "8·5." }, tip: "8 · ? = 48", successText: "Kiste zu!", pureMath: false },
  { id: "ul-09", zone: "umkehr-laden", mission: "ul-m2", sceneText: "25 = 5 · ?", question: "5 · ?", answers: ["4", "5", "6", "20"], correctAnswer: "5", feedback: { "4": "Zu wenig.", "6": "Zu viel.", "20": "5·4." }, tip: "5er-Reihe", successText: "Stapel fertig!", pureMath: true },
  { id: "ul-10", zone: "umkehr-laden", mission: "ul-m2", sceneText: "? · 8 = 56", question: "? · 8 = 56", answers: ["6", "7", "8", "48"], correctAnswer: "7", feedback: { "6": "Zu wenig.", "8": "Zu viel.", "48": "6·8." }, tip: "8er bis 56", successText: "Regale fertig!", pureMath: true },
  { id: "ul-11", zone: "umkehr-laden", mission: "ul-m3", sceneText: "30 Stifte, 5 Kinder.", question: "Jedes Kind?", answers: ["5", "6", "7", "25"], correctAnswer: "6", feedback: { "5": "Zu wenig.", "7": "Zu viel.", "25": "5·5." }, tip: "5 · ?", successText: "Stifte geteilt!", pureMath: false },
  { id: "ul-12", zone: "umkehr-laden", mission: "ul-m3", sceneText: "2 · 10 = ?", question: "2 Packungen à 10?", answers: ["12", "18", "20", "210"], correctAnswer: "20", feedback: { "12": "Plus.", "18": "Falsch.", "210": "Mal." }, tip: "10 + 10", successText: "Packung fertig!", pureMath: true },
  { id: "ul-13", zone: "umkehr-laden", mission: "ul-m3", sceneText: "18 = 2 · ?", question: "2 gleiche Gruppen?", answers: ["8", "9", "10", "16"], correctAnswer: "9", feedback: { "8": "Zu wenig.", "10": "Zu viel.", "16": "2·8." }, tip: "2 · ?", successText: "Gleich verteilt!", pureMath: false },
  { id: "ul-14", zone: "umkehr-laden", mission: "ul-m3", sceneText: "4 · 7 = ?", question: "4 · 7 = ?", answers: ["11", "24", "28", "47"], correctAnswer: "28", feedback: { "11": "Plus.", "24": "Zu wenig.", "47": "Mal." }, tip: "4er oder 7er", successText: "Material fertig!", pureMath: true },
  { id: "ul-15", zone: "umkehr-laden", mission: "ul-m3", sceneText: "45 = 9 · ?", question: "9 · ?", answers: ["4", "5", "6", "36"], correctAnswer: "5", feedback: { "4": "Zu wenig.", "6": "Zu viel.", "36": "9·4." }, tip: "9er-Reihe", successText: "Laden bereit!", pureMath: true },

  { id: "kt-01", zone: "knobel-turm", mission: "kt-m1", sceneText: "Im Turm: 25 + 30 + 5.", question: "Rechenweg: Ergebnis?", answers: ["50", "55", "60", "25305"], correctAnswer: "60", feedback: { "50": "Einer fehlen.", "55": "Fast.", "25305": "Schrittweise." }, tip: "25+30, dann +5", successText: "Eine Stufe höher!", pureMath: false },
  { id: "kt-02", zone: "knobel-turm", mission: "kt-m1", sceneText: "3 + 4 · 2 (Punkt vor Strich)", question: "Ergebnis?", answers: ["14", "11", "10", "20"], correctAnswer: "11", feedback: { "14": "Erst Mal, dann Plus.", "10": "Falsch.", "20": "4·2 zuerst." }, tip: "Erst 4·2, dann +3", successText: "Tür geht auf!", pureMath: false },
  { id: "kt-03", zone: "knobel-turm", mission: "kt-m1", sceneText: "(2 + 3) · 4", question: "Ergebnis?", answers: ["14", "20", "24", "9"], correctAnswer: "20", feedback: { "14": "Klammer zuerst.", "24": "Falsch.", "9": "Nur Klammer." }, tip: "2+3=5, dann ·4", successText: "Weiter klettern!", pureMath: false },
  { id: "kt-04", zone: "knobel-turm", mission: "kt-m1", sceneText: "50 − 20 − 10", question: "Ergebnis?", answers: ["20", "30", "40", "10"], correctAnswer: "20", feedback: { "30": "Nur ein Minus.", "40": "Plus.", "10": "Zu viel minus." }, tip: "Schritt für Schritt", successText: "Leiter fest!", pureMath: true },
  { id: "kt-05", zone: "knobel-turm", mission: "kt-m1", sceneText: "10 + 10 + 10 + 10", question: "Schneller Rechenweg?", answers: ["30", "40", "50", "10101010"], correctAnswer: "40", feedback: { "30": "Einer fehlt.", "50": "Einer zu viel.", "10101010": "4·10." }, tip: "4 · 10", successText: "Oben sichtbar!", pureMath: false },
  { id: "kt-06", zone: "knobel-turm", mission: "kt-m2", sceneText: "2 · 6 + 5", question: "Ergebnis?", answers: ["17", "22", "12", "72"], correctAnswer: "17", feedback: { "22": "Mal zuerst.", "12": "Nur Mal.", "72": "Falsch." }, tip: "2·6, dann +5", successText: "Rätsel gelöst!", pureMath: false },
  { id: "kt-07", zone: "knobel-turm", mission: "kt-m2", sceneText: "100 − 25 − 25", question: "Ergebnis?", answers: ["25", "50", "75", "150"], correctAnswer: "50", feedback: { "25": "Noch ein Minus.", "75": "Nur ein Minus.", "150": "Plus." }, tip: "100−25=75, noch −25", successText: "Schloss knackt!", pureMath: true },
  { id: "kt-08", zone: "knobel-turm", mission: "kt-m2", sceneText: "5 · 5 + 5", question: "Ergebnis?", answers: ["25", "30", "35", "55"], correctAnswer: "30", feedback: { "25": "Nur 5·5.", "35": "Zu viel.", "55": "Anhängen." }, tip: "25+5", successText: "Fast am Schatz!", pureMath: false },
  { id: "kt-09", zone: "knobel-turm", mission: "kt-m2", sceneText: "8 · 4 − 10", question: "Ergebnis?", answers: ["22", "32", "42", "18"], correctAnswer: "22", feedback: { "32": "Minus vergessen.", "42": "Plus.", "18": "Falsch." }, tip: "32−10", successText: "Turm geschafft!", pureMath: false },
  { id: "kt-10", zone: "knobel-turm", mission: "kt-m2", sceneText: "(10 − 4) · 2", question: "Ergebnis?", answers: ["8", "12", "16", "6"], correctAnswer: "12", feedback: { "8": "Klammer.", "16": "Falsch.", "6": "Nur Klammer." }, tip: "6·2", successText: "Knobel-Turm frei!", pureMath: false },

  { id: "sp-01", zone: "schatzplatz", mission: "sp-m1", sceneText: "Letzte Lichter: 10 weniger als 95.", question: "Ergebnis?", answers: ["85", "94", "105", "75"], correctAnswer: "85", feedback: { "94": "Nur 1.", "105": "Mehr.", "75": "20 weniger." }, tip: "95−10", successText: "Ein Licht mehr!", pureMath: false },
  { id: "sp-02", zone: "schatzplatz", mission: "sp-m1", sceneText: "Festkuchen: 64 − 27.", question: "Stücke übrig?", answers: ["37", "47", "57", "91"], correctAnswer: "37", feedback: { "47": "Zu viel.", "57": "Zu viel.", "91": "Plus." }, tip: "64−27", successText: "Kuchen reicht!", pureMath: true },
  { id: "sp-03", zone: "schatzplatz", mission: "sp-m1", sceneText: "Am Festplatz: 7 · 8.", question: "Stühle in 7 Reihen à 8?", answers: ["15", "48", "56", "78"], correctAnswer: "56", feedback: { "15": "Plus.", "48": "Zu wenig.", "78": "Mal." }, tip: "8er-Reihe", successText: "Alle Stühle!", pureMath: false },
  { id: "sp-04", zone: "schatzplatz", mission: "sp-m1", sceneText: "? + 35 = 100 für Dekoration.", question: "Fehlender Betrag?", answers: ["55", "65", "75", "135"], correctAnswer: "65", feedback: { "55": "Zu wenig.", "75": "Zu viel.", "135": "100 Ziel." }, tip: "100−35", successText: "Deko komplett!", pureMath: true },
  { id: "sp-05", zone: "schatzplatz", mission: "sp-m1", sceneText: "53 + 38 für Gäste.", question: "Gäste gesamt?", answers: ["81", "91", "101", "915"], correctAnswer: "91", feedback: { "81": "Übergang.", "101": "Zu viel.", "915": "Plus." }, tip: "Einer, Zehner", successText: "Fest fast bereit!", pureMath: true },
  { id: "sp-06", zone: "schatzplatz", mission: "sp-m2", sceneText: "Schatz-Rätsel: 85 hat 8 Zehner und 5 Einer.", question: "Stimmt die Zahl?", answers: ["Ja, 85", "Nein, 58", "Nein, 805", "Nein, 13"], correctAnswer: "Ja, 85", feedback: { "Nein, 58": "Vertauscht.", "Nein, 805": "Zu groß.", "Nein, 13": "8+5." }, tip: "80+5", successText: "Erster Schlüssel!", pureMath: false },
  { id: "sp-07", zone: "schatzplatz", mission: "sp-m2", sceneText: "3 + 4 · 2 für die Truhe.", question: "Code-Zahl?", answers: ["14", "11", "10", "24"], correctAnswer: "11", feedback: { "14": "Mal zuerst.", "10": "Falsch.", "24": "Falsch." }, tip: "Punkt vor Strich", successText: "Truhe wackelt!", pureMath: false },
  { id: "sp-08", zone: "schatzplatz", mission: "sp-m2", sceneText: "? · 8 = 48", question: "Letzte Gruppe?", answers: ["5", "6", "7", "8"], correctAnswer: "6", feedback: { "5": "Zu wenig.", "7": "Zu viel.", "8": "8·8=64." }, tip: "8er-Reihe", successText: "Schloss offen!", pureMath: false },
  { id: "sp-09", zone: "schatzplatz", mission: "sp-m2", sceneText: "92 Seiten Buch, 40 gelesen.", question: "Seiten fehlen?", answers: ["52", "62", "132", "9240"], correctAnswer: "52", feedback: { "62": "Zu viel.", "132": "Plus.", "9240": "Minus." }, tip: "92−40", successText: "Fast geschafft!", pureMath: false },
  { id: "sp-10", zone: "schatzplatz", mission: "sp-m2", sceneText: "58 ___ 85 — letzter Wegweiser.", question: "Zeichen?", answers: ["<", ">", "=", "+"], correctAnswer: "<", feedback: { ">": "58 kleiner.", "=": "Ungleich.", "+": "Vergleich." }, tip: "Zehner!", successText: "Der Schatz ist da!", pureMath: true }
];

// Ergänzung: problemText für jede Aufgabe
// (Damit der Missionsscreen klar Trennt: Szene -> Problem -> Frage)
function buildProblemText(task) {
  if (!task || !task.zone) return "Hilf der Stadt beim Mathe-Fest. Welche Antwort passt?";
  if (task.zone === "zahlen-tor") {
    return "Der Torwächter braucht deine Hilfe beim Mathe-Fest. Welche Zahl passt?";
  }
  if (task.zone === "baecker-gasse") {
    return "Die Bäckerin braucht deine Hilfe. Welche Zahl gehört zum nächsten Schritt im Fest?";
  }
  if (task.zone === "bus-platz") {
    return "Der Busfahrer braucht deine Hilfe. Hilf ihm, die richtige Zahl zu finden.";
  }
  if (task.zone === "einmaleins-werkstatt") {
    return "In der Werkstatt läuft die Maschine nur mit der richtigen Zahl.";
  }
  if (task.zone === "umkehr-laden") {
    return "Im Umkehr-Laden sollen alle Körbe gleich gefüllt sein. Welche Zahl passt?";
  }
  if (task.zone === "knobel-turm") {
    return "Am Knobel-Turm braucht es einen klugen Rechenweg. Welche Antwort passt?";
  }
  if (task.zone === "schatzplatz") {
    return "Zum Mathe-Schatz fehlt noch die richtige Lösung.";
  }
  return "Hilf der Stadt beim Mathe-Fest. Welche Antwort passt?";
}

for (var i = 0; i < TASK_BANK.length; i++) {
  if (!TASK_BANK[i].problemText) {
    TASK_BANK[i].problemText = buildProblemText(TASK_BANK[i]);
  }
}
